#cloud-config
coreos:
  etcd2:
    discovery: https://discovery.etcd.io/a95dfc8717ac2bcd08b9b4ec6056b7a6
    advertise-client-urls: "http://$private_ipv4:2379"
    initial-advertise-peer-urls: "http://$private_ipv4:2380"
    listen-client-urls: "http://0.0.0.0:2379,http://0.0.0.0:4001"
    listen-peer-urls: "http://$private_ipv4:2380,http://$private_ipv4:7001"
    data-dir: /var/lib/etcd2
  fleet:
    public-ip: $private_ipv4
    etcd_servers: "http://$private_ipv4:2379"
  flannel:
    interface: $private_ipv4
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: flanneld.service
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config \
              '{ "Network": "10.10.0.0/16" }'
      command: start
ssh_authorized_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOYAJq8CPJTjaPbx4MB1v40UB8P1ZLPK59JuUpLb8vRl+iQOowq+IVV1euRu5kJaLyMrk9xPwC7+SVdFVQS6zHHaH08Jc9vS6cRrs4vBkMQ/anVhya7NfT1SKL1i8YsZ4Qkf7J2CMAcluGnyeOeYg9rkSWdKyi8u/7MnbQj5atcKGz/ogSuj4VIWDMcN3uSHxxTpih8B3Y/lgV4tUKnbbFg4bRlfgvHLVSraUHCQMtm1Fbnl8UugQwbJoSaQVoQ8E2WRUV7gAfh2AdplNz98yFY6BaZzKoSwFE3kCpEWuUDILb/BVVPYUZHM8X/Jhoc1VcqyUnaL+GNvh+LXDd+qLB root@rohith-PC"
